# Basic
title: STUNUM
subtitle: 面有萌色，胸有丘壑。心有猛虎，细嗅蔷薇。
welcome_message: Python web开发，后端以Django框架为主，前端使用Vue.js...
description: 嗨，我是王鑫 (@stunum)，一名 Python 开发者。
creator: <a href="http://stunum.com">@stunum</a>

url: "https://stunum.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
  title: 博客
  description: 访问博客

nav:
  - {
      title: 简历,
      description: 我的简历,
      url: "https://media.stunum.com/python%E5%BC%80%E5%8F%91_%E7%8E%8B%E9%91%AB_15669313370.pdf",
    }
  - { title: 愿望清单, description: 我愿望清单, url: "/wishlist" }
  - { title: 工具, description: 我所使用的开发工具, url: "/apps" }

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
  disqus: stunum

social:
  weibo: stunum_
  github: stunum
  mail: 419400431@qq.com
